# Generated by Django 2.2.5 on 2019-09-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0002_auto_20190926_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcontract',
            name='contractType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionApp.PatentConcept', verbose_name='Tipo de Contrato'),
        ),
    ]
