# Generated by Django 2.2.5 on 2019-09-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0003_auto_20190926_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentcontract',
            options={'verbose_name': 'Contrato Empresa', 'verbose_name_plural': 'Contratos Empresas'},
        ),
        migrations.AlterModelOptions(
            name='patentconcept',
            options={'verbose_name': 'Concepto de la patente', 'verbose_name_plural': 'Conceptos de las patentes o tipos'},
        ),
    ]
