# Generated by Django 2.2.5 on 2019-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0004_auto_20190926_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentconcept',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
