# Generated by Django 2.2.5 on 2019-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0006_currentcontract_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcontract',
            name='upLoadFile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ficheros del contrato'),
        ),
    ]
