# Generated by Django 2.2.5 on 2019-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0007_auto_20191001_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecontract',
            name='upLoadFile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ficheros del contrato'),
        ),
    ]
