# Generated by Django 2.2.5 on 2019-11-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0009_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcontract',
            name='expired',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vencido'),
        ),
        migrations.AddField(
            model_name='privatecontract',
            name='expired',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vencido'),
        ),
    ]
