# Generated by Django 2.2.5 on 2019-12-09 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0014_auto_20191208_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='contractType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionApp.PatentConcept', verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='expired',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vencido'),
        ),
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='headline',
            field=models.CharField(default='', max_length=250, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='paymentType',
            field=models.CharField(default='', max_length=100, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='supplement',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Suplemento'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 23, 28, 46, 546942), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 23, 28, 46, 546889), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 23, 28, 46, 548623), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 23, 28, 46, 548582), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 23, 28, 46, 550184), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 23, 28, 46, 550143), verbose_name='Fecha Inicio'),
        ),
    ]
