# Generated by Django 2.2.5 on 2019-12-09 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0015_auto_20191208_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 466578), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 466532), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 469515), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 469476), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 470997), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 470958), verbose_name='Fecha Inicio'),
        ),
        migrations.CreateModel(
            name='AuditPrivateContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('userName', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('contractNumber', models.CharField(blank=True, max_length=250, null=True, verbose_name='Número de contrato')),
                ('supplement', models.CharField(blank=True, max_length=250, null=True, verbose_name='Suplemento')),
                ('newStartDate', models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 468057), verbose_name='Fecha Inicio')),
                ('newEndDate', models.DateTimeField(default=datetime.datetime(2019, 12, 9, 11, 43, 42, 468101), verbose_name='Fecha Vence')),
                ('action', models.CharField(blank=True, max_length=250, null=True, verbose_name='accion que realizo')),
                ('patentNumber', models.CharField(max_length=250, verbose_name='Número de patente')),
                ('headline', models.CharField(default='', max_length=250, verbose_name='Titular')),
                ('ciNumber', models.CharField(blank=True, max_length=11, unique=True, verbose_name='Carnet Identidad')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('value', models.FloatField(default=0, verbose_name='Monto de pago')),
                ('paymentType', models.CharField(default='', max_length=100, verbose_name='Forma de pago')),
                ('expired', models.BooleanField(blank=True, null=True, verbose_name='Vencido')),
                ('patentConcept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionApp.PatentConcept', verbose_name='Concepto de la patente')),
            ],
        ),
    ]
