# Generated by Django 2.2.5 on 2019-12-17 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0017_auto_20191209_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Suplemento')),
            ],
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 27114), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 27070), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 28597), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 28553), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 30563), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 30524), verbose_name='Fecha Inicio'),
        ),
        migrations.RemoveField(
            model_name='currentcontract',
            name='supplement',
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 33115), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 15, 23, 58, 33076), verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='currentcontract',
            name='supplement',
            field=models.ManyToManyField(max_length=250, to='contratacionApp.Supplement', verbose_name='Suplemento'),
        ),
    ]
