# Generated by Django 2.2.5 on 2019-12-18 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0019_auto_20191217_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 409875), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 409829), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 411480), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 411232), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 413604), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 413563), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 416371), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 50, 8, 416331), verbose_name='Fecha Inicio'),
        ),
        migrations.RemoveField(
            model_name='privatecontract',
            name='supplement',
        ),
        migrations.AddField(
            model_name='privatecontract',
            name='supplement',
            field=models.ManyToManyField(max_length=250, to='contratacionApp.Supplement', verbose_name='Suplemento'),
        ),
    ]
