# Generated by Django 2.2.5 on 2019-12-18 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0021_auto_20191217_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 662687), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 662639), verbose_name='Fecha Inicio'),
        ),
        migrations.RemoveField(
            model_name='auditcurrentcontract',
            name='supplement',
        ),
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='supplement',
            field=models.ManyToManyField(max_length=250, to='contratacionApp.Supplement', verbose_name='Suplemento'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 665339), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 665299), verbose_name='Fecha Inicio'),
        ),
        migrations.RemoveField(
            model_name='auditprivatecontract',
            name='supplement',
        ),
        migrations.AddField(
            model_name='auditprivatecontract',
            name='supplement',
            field=models.ManyToManyField(max_length=250, to='contratacionApp.Supplement', verbose_name='Suplemento'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 667868), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 667827), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 670575), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 16, 29, 670536), verbose_name='Fecha Inicio'),
        ),
    ]
