# Generated by Django 2.2.5 on 2020-02-12 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionApp', '0027_auto_20200211_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentcontract',
            name='numberRegistration',
            field=models.CharField(default=0, max_length=250, verbose_name='Número de Registro'),
        ),
        migrations.AddField(
            model_name='auditprivatecontract',
            name='numberRegistration',
            field=models.CharField(default=0, max_length=250, verbose_name='Número de Registro'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 323295), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditcurrentcontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 323295), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newEndDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 326293), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='auditprivatecontract',
            name='newStartDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 326293), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 328291), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='currentcontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 328291), verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 330290), verbose_name='Fecha Vence'),
        ),
        migrations.AlterField(
            model_name='privatecontract',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 22, 11, 34, 330290), verbose_name='Fecha Inicio'),
        ),
    ]
